/**
 * List of all the boilerplate github repositories that I have found.
 *
 * Most entries are a string indicating the repository URL.
 *
 * Special cases require an object to be be used with more options:
 *  - location of package.json file(s)
 *  - force project to have a tag (if autotagging isn't working)
 *  - force project to NOT have a tag (if autotagging isn't working)
 */
module.exports = [
  // package.json in project root
  'https://github.com/a-tarasyuk/rr-boilerplate',
  'https://github.com/acdlite/flummox-isomorphic-demo',
  'https://github.com/adampash/react-native-hot-redux-starter',
  'https://github.com/alicoding/react-webpack-babel',
  'https://github.com/anorudes/redux-easy-boilerplate',
  'https://github.com/atSistemas/react-base',
  'https://github.com/BackSpaceTech/react-bootstrap-boilerplate',
  'https://github.com/balupton/minimal-react',
  'https://github.com/barbar/vortigern',
  'https://github.com/bartonhammond/snowflake',
  'https://github.com/bharani91/react-express-starter',
  'https://github.com/birkir/react-typescript-iso-kit',
  'https://github.com/bradleyboy/yarsk',
  'https://github.com/catalin-luntraru/redux-minimal',
  'https://github.com/cdebotton/react-universal',
  'https://github.com/cloudmu/react-redux-starter-kit',
  'https://github.com/codefoundries/UniversalRelayBoilerplate',
  'https://github.com/coryhouse/react-flux-starter-kit',
  'https://github.com/coryhouse/react-slingshot',
  'https://github.com/davezuko/react-redux-starter-kit',
  'https://github.com/dvajs/dva',
  'https://github.com/DominicTobias/universal-react',
  'https://github.com/dozoisch/koa-react-full-example',
  'https://github.com/eanplatter/react-starter',
  'https://github.com/elierotenberg/react-rails-starterkit',
  'https://github.com/ericelliott/react-pure-component-starter',
  'https://github.com/erikras/react-redux-universal-hot-example',
  'https://github.com/este/este',
  'https://github.com/foxhound87/rfx-stack',
  'https://github.com/futurice/pepperoni-app-kit',
  'https://github.com/gaearon/react-hot-boilerplate',
  'https://github.com/goshakkk/no-bs-react-webpack-starter',
  'https://github.com/Granze/react-starterify',
  'https://github.com/iam4x/isomorphic-flux-boilerplate',
  'https://github.com/irvinebroque/isomorphic-hot-loader',
  'https://github.com/ivanzotov/react-native-example',
  'https://github.com/janoist1/universal-react-redux-starter-kit',
  'https://github.com/jaredpalmer/react-production-starter',
  'https://github.com/jcreamer898/expressiso',
  'https://github.com/jedireza/aqua',
  'https://github.com/jeffschwartz/react-quickstart',
  'https://github.com/jim-y/fluxury',
  'https://github.com/jkup/react-app-starter',
  'https://github.com/khalilgharbaoui/flux-boilerplate',
  'https://github.com/koba04/react-boilerplate',
  'https://github.com/krasimir/react-webpack-starter',
  'https://github.com/kriasoft/aspnet-starter-kit',
  'https://github.com/kriasoft/babel-starter-kit',
  'https://github.com/kriasoft/react-starter-kit',
  'https://github.com/kriasoft/react-static-boilerplate',
  'https://github.com/KyleAMathews/coffee-react-quickstart',
  'https://github.com/lubien/koa-react-redux-universal-boilerplate',
  'https://github.com/lynnaloo/mullet',
  'https://github.com/MadeInHaus/react-flux-gulp-starter',
  'https://github.com/madnight/react-webpack-babel-karma-boilerplate',
  'https://github.com/mcnamee/react-native-starter-app',
  'https://github.com/mhart/simple-relay-starter',
  'https://github.com/mikechabot/react-boilerplate',
  'https://github.com/mobxjs/mobx-react-boilerplate',
  'https://github.com/MoOx/phenomic',
  'https://github.com/mxstbr/react-boilerplate',
  'https://github.com/ngduc/react-setup',
  'https://github.com/nicholaswyoung/react-boilerplate',
  'https://github.com/NYTimes/kyt',
  'https://github.com/olebedev/go-starter-kit',
  'https://github.com/osxi/react-pouch-redux-starter-kit',
  'https://github.com/PBRT/reactogo',
  'https://github.com/peter-mouland/react-lego',
  'https://github.com/pheuter/essential-react',
  'https://github.com/piotrwitek/react-redux-typescript-starter-kit',
  'https://github.com/przeor/react-router-flux-starter-kit',
  'https://github.com/rangle/react-redux-example',
  'https://github.com/rauschma/react-starter-project',
  'https://github.com/rbartoli/react-boilerplate',
  'https://github.com/reactGo/reactGo',
  'https://github.com/RickWong/react-isomorphic-starterkit',
  'https://github.com/rofrol/react-starter-kit',
  'https://github.com/RyanCCollins/scalable-react-boilerplate',
  'https://github.com/saikat/react-apollo-starter-kit',
  'https://github.com/skolmer/react-hot-boilerplate-vscode',
  'https://github.com/stample/gulp-browserify-react-phonegap-starter',
  'https://github.com/start-react/native-starter-kit',
  'https://github.com/stoikerty/dev-toolkit',
  'https://github.com/substack/react-starter-hmr',
  'https://github.com/survivejs/react-component-boilerplate',
  'https://github.com/tinkertrain/jspm-react',
  'https://github.com/tosFa/react-cross-platform-boardgame-example',
  'https://github.com/tpai/r2-starter-kit',
  'https://github.com/unicorn-standard/starter-kit',
  'https://github.com/vasanthk/react-universal-starter',
  'https://github.com/vesparny/react-kickstart',
  'https://github.com/VodkaBears/another-one-fucking-boilerplate',
  'https://github.com/vutran/spa-starter-kit',
  'https://github.com/wbkd/react-starterkit',
  'https://github.com/wdjungst/react-project',
  'https://github.com/weblancaster/node-react-stack-kit',
  'https://github.com/webpack/react-starter',
  'https://github.com/wwsun/starter-node-react',
  'https://github.com/xpepermint/isomorphic-react-relay-boilerplate',
  'https://github.com/zxbodya/reactive-widgets',

  // package.json elsewhere, or needs tag adjustments
  {
    url: 'https://github.com/facebookincubator/create-react-app',
    nonTags: ['CSS Modules'],
  },
  {
    url: 'https://github.com/ahfarmer/minimal-react-starter',
    additionalTags: ['HMR'],
  },
  {
    url: 'https://github.com/FredericHeem/starhackit',
    packagePaths: [
      'client/package.json',
      'server/package.json',
    ],
  },
  {
    url: 'https://github.com/kjda/ReactJs-Phonegap',
    packagePaths: [
      'app/package.json',
      'server/package.json',
    ],
  },
  {
    url: 'https://github.com/geowarin/boot-react',
    packagePaths: [
      'frontend/package.json',
    ],
  },
  {
    url: 'https://github.com/pauldotknopf/react-aspnet-boilerplate',
    packagePaths: [
      'src/ReactBoilerplate/package.json',
    ],
  },
  {
    url: 'https://github.com/aspnet/JavaScriptServices',
    packagePaths: [
      'templates/ReactSpa/package.json',
    ],
  },
];
